[workspace]
resolver = "2"
members = [
    "crates/ritornello-proto",
    "crates/ritornello-i18n",
    "crates/ritornello-plugin-sdk",
    "crates/ritornello-core",
    "crates/ritornello-plugin-radio",
    "crates/ritornello-plugin-cd",
    "crates/ritornello-plugin-musicbrainz",
    "crates/ritornello-plugin-ouifm-metas",
    "crates/ritornello-plugin-radiofrance-metas",
    "crates/ritornello-plugin-files",
    "crates/ritornello-plugin-console",
    "crates/ritornello-plugin-generic-input",
    "crates/ritornello-plugin-mpd",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/skerdudou/ritornello"
