[workspace]
resolver = "2"
members = [
    "crates/ritornello-proto",
    "crates/ritornello-i18n",
    "crates/ritornello-plugin-sdk",
    "crates/ritornello-core",
    "crates/ritornello-plugin-radio",
    "crates/ritornello-plugin-cd",
    "crates/ritornello-plugin-console",
    "crates/ritornello-plugin-mce",
]
