[package]
name = "ritornello-plugin-radio"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ritornello-plugin-radio"
path = "src/main.rs"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait = "0.1"
ritornello-proto = { path = "../ritornello-proto" }
ritornello-plugin-sdk = { path = "../ritornello-plugin-sdk" }

[dev-dependencies]
tempfile = "3"
