[[plugin]]
name = "radio"
kind = "source"
exec = "/usr/local/lib/ritornello/plugins/ritornello-plugin-radio"
admin = true

[[plugin]]
name = "cd"
kind = "source"
exec = "/usr/local/lib/ritornello/plugins/ritornello-plugin-cd"

[[plugin]]
name = "mce"
kind = "input"
exec = "/usr/local/lib/ritornello/plugins/ritornello-plugin-mce"

[[plugin]]
name = "console"
kind = "display"
exec = "/usr/local/lib/ritornello/plugins/ritornello-plugin-console"
